feign:
  compression:
    request:
      enabled: true
      mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
      min-request-size: 0
    response:
      enabled: true
server:
  port: 8002